<br/>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
  如果感觉这篇文章对你有帮助，网站希望能得到您的捐赠：<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="4C4LQEJL29US6">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
<br/>