<script type="text/javascript">
	window._qzone_share_pick_cfg = {
		url:location.href,
		summary:'',/*分享摘要(可选)*/
		title:'',/*分享标题(可选)*/
		site:'',/*分享来源 如：腾讯网(可选)*/
		pics:'', /*分享图片的路径(可选)*/
		drag_pick:{
				'@style':103,
				body:{}
			}
	};
</script>
<script type="text/javascript" src="http://qzonestyle.gtimg.cn/qzone/app/qzshare/script/qzshare.plus.pick.js" async="true" charset="utf-8"></script>
