<script type="text/javascript"> 
clicksor_adhere_opt='right:100%'; 

clicksor_default_url = '';
clicksor_banner_border = '#99CC33'; 
clicksor_banner_ad_bg = '#FFFFFF';
clicksor_banner_link_color = '#000000'; 
clicksor_banner_text_color = '#666666';
clicksor_layer_border_color = '';
clicksor_layer_ad_bg = ''; 
clicksor_layer_ad_link_color = '';
clicksor_layer_ad_text_color = ''; 
clicksor_text_link_bg = '';
clicksor_text_link_color = ''; 
clicksor_enable_text_link = false;
		 
clicksor_banner_text_banner = true;
clicksor_banner_image_banner = true; 
clicksorcn_enable_layer_pop = false;
</script>
<script type="text/javascript" src="http://ads.clicksor.com/newServing/showAd.php?nid=1&amp;pid=320206&amp;adtype=9&amp;sid=533404"></script> <noscript><a href="http://www.yesads.com">online marketing</a></noscript>