<FORM name="searchbox" action="http://search.clicksor.com/newServing/yesupSearch/web.php" method="post">
<div id="search" class="box">
  <div class="box">
    <div id="search-input">
      <input type="text" name="q" size="40" value=""/>
      <input type="hidden" name="nid"  value="1"/>
      <input type="hidden" name="pid"  value="320206"/>
      <input type="hidden" name="sid"  value="533404"/>
    </div>
    <div id="search-submit">
      <input type="submit" name="submit" value="" style="border:#707070 0px solid;cursor:hand;width:29px; height:30px;background-image:url('../images/site/search-submit.gif')" class="button_green"/>
    </div>
  </div>
</div>
</FORM>
<!--#include file="../../inc/ads/clicksor/searchbox.inc"-->