<!--l version="1.0" encoding="utf-8"-->
<div class="kj mt1"><a target="_blank" href="http://www.haocaile.com/customer/register.html">&nbsp;</a><img alt="" src="../UserFiles/pic_r.gif" /></div>
<!-- /zhongjianggonggao -->
<div class="commend mt1"><dl class="tbox light"><dt class="light"><strong>中奖播报</strong> </dt><dd class="light">
<ul class="c1 ico2"><!--- <li class='dotline'><b>whuaffa</b>喜中江双色球<span class="red">￥980.00元</span></li>
            <li class='dotline'><b>whusfsa</b>喜中江西时时彩<span class="red">￥4440.00元</span></li>
            <li class='dotline'><b>whuda</b>喜中福彩3D<span class="red">￥98440.00元</span></li>
            <li class='dotline'><b>whusfa</b>喜中江西时时彩<span class="red">￥440.00元</span></li>
            <li class='dotline'><b>whusfa</b>喜中江西时时彩<span class="red">￥442142.00元</span></li>
            <li class='dotline'><b>whuaffa</b>喜中江双色球<span class="red">￥980.00元</span></li>
            <li class='dotline'><b>whusfsa</b>喜中江西时时彩<span class="red">￥4440.00元</span></li>
            <li class='dotline'><b>whuda</b>喜中福彩3D<span class="red">￥98440.00元</span></li>
            <li class='dotline'><b>whusfa</b>喜中江西时时彩<span class="red">￥440.00元</span></li>
            <li class='dotline'><b>whusfa</b>喜中江西时时彩<span class="red">￥442142.00元</span></li> ---></ul>
    </dd></dl></div>
    <!-- /zhongjiangbobao -->
    <div class="hot mt1"><dl class="tbox light"><dt class="light"><strong>走势图表</strong> </dt><dd class="light">
    <ul class="c1 ico2">
        <li class="dotline"><a target="_blank" href="http://www.jincaizi.com/ssq/ssqzst.jhtml">双色球走势图</a> </li>
        <li class="dotline"><a target="_blank" href="http://www.jincaizi.com/fc3d/fc3dzst.jhtml">福彩3D走势图</a> </li>
        <li class="dotline"><a target="_blank" href="http://www.jincaizi.com/dlt/dltzst.jhtml">大乐透走势图</a> </li>
        <li class="dotline"><a target="_blank" href="http://www.jincaizi.com/p3/p3zst.jhtml">排列3走势图</a> </li>
        <li class="dotline"><a target="_blank" href="http://www.jincaizi.com/cqssc/cqssczst.jhtml">时时彩走势图</a> </li>
        <li class="dotline"><a target="_blank" href="http://zst.jincaizi.com/tendency/jx11x5/distributedChart.jhtml">江西11选5走势图</a> </li>
        <li class="dotline"><a target="_blank" href="http://zst.jincaizi.com/tendency/sd11x5/distributedChart.jhtml">十一运夺金走势图</a> </li>
    </ul>
    </dd></dl></div>