<div id="menu_out">
  <div id="menu_in">
    <div id="menu">
      <ul id="nav">
        <li>
          <a class="nav_on" id="mynav0" onmouseover="javascript:qiehuan(0)" href="../index.html">
            <span>首 页</span>
          </a>
        </li>
        <li class="menu_line"></li>
        <li>
          <a href="#" onmouseover="javascript:qiehuan(1)" id="mynav1" class="nav_off">
            <span>
              新闻
            </span>
          </a>
        </li>
        <li class="menu_line"></li>
        <li>
          <a href="#" onmouseover="javascript:qiehuan(2)" id="mynav2" class="nav_off">
            <span>
              团购
            </span>
          </a>
        </li>
        <li class="menu_line"></li>
        <li>
          <a href="#" onmouseover="javascript:qiehuan(3)" id="mynav3" class="nav_off">
            <span>
              商城
            </span>
          </a>
        </li>
        <li class="menu_line"></li>
        <li>
          <a href="#" onmouseover="javascript:qiehuan(4)" id="mynav4" class="nav_off">
            <span>
              书店
            </span>
          </a>
        </li>
        <li class="menu_line"></li>
        <li>
          <a href="#" onmouseover="javascript:qiehuan(5)" id="mynav5" class="nav_off">
            <span>
              旅游
            </span>
          </a>
        </li>
        <li class="menu_line"></li>
        <li>
          <a href="#" onmouseover="javascript:qiehuan(6)" id="mynav6" class="nav_off">
            <span>
              美食
            </span>
          </a>
        </li>
        <li class="menu_line"></li>
        <li>
          <a href="#" onmouseover="javascript:qiehuan(7)" id="mynav7" class="nav_off">
            <span>
              男/女装
            </span>
          </a>
        </li>
        <li class="menu_line"></li>
        <li>
          <a class="nav_off" id="mynav8" onmouseover="javascript:qiehuan(8)" href="#">
            <span>
              博客
            </span>
          </a>
        </li>
        <li class="menu_line"></li>
        <li>
          <a class="nav_off" id="mynav9" onmouseover="javascript:qiehuan(9)" href="#" target="_blank">
            <span>论坛</span>
          </a>
        </li>
        <li class="menu_line"></li>
      </ul>
      <div id="menu_con">
        <div id="qh_con0" style="display: block">
          <ul>
            <li>
              <a href="#">
                <span>栏目名称1</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称2</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称3</span>
              </a>
            </li>
          </ul>
        </div>
        <div id="qh_con1" style="display: none">
          <ul>
            <li>
              <a href="#">
                <span>栏目名称4</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称5</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称6</span>
              </a>
            </li>
          </ul>
        </div>
        <div id="qh_con2" style="display: none">
          <ul>
            <li>
              <a href="#">
                <span>栏目名称7</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称8</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称9</span>
              </a>
            </li>
          </ul>
        </div>
        <div id="qh_con3" style="display: none">
          <ul>
            <li>
              <a href="#">
                <span>栏目名称10</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称11</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称12</span>
              </a>
            </li>
          </ul>
        </div>
        <div id="qh_con4" style="display: none">
          <ul>
            <li>
              <a href="#">
                <span>栏目名称13</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称14</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称15</span>
              </a>
            </li>
          </ul>
        </div>
        <div id="qh_con5" style="display: none">
          <ul>
            <li>
              <a href="#">
                <span>栏目名称16</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称17</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称18</span>
              </a>
            </li>
          </ul>
        </div>
        <div id="qh_con6" style="display: none">
          <ul>
            <li>
              <a href="#">
                <span>栏目名称19</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称20</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称21</span>
              </a>
            </li>
          </ul>
        </div>
        <div id="qh_con7" style="display: none">
          <ul>
            <li>
              <a href="#">
                <span>栏目名称22</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称23</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称24</span>
              </a>
            </li>
          </ul>
        </div>
        <div id="qh_con8" style="display: none">
          <ul>
            <li>
              <a href="#">
                <span>栏目名称25</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称26</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称27</span>
              </a>
            </li>
          </ul>
        </div>
        <div id="qh_con9" style="display: none">
          <ul>
            <li>
              <a href="#">
                <span>栏目名称28</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称29</span>
              </a>
            </li>
            <li class="menu_line2"></li>
            <li>
              <a href="#">
                <span>栏目名称30</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>