<pre>
  亲爱的用户 {0}：您好！<br/>
    <br/>
      感谢您注册SYIHY社区，您只需要点击下面链接，激活您的帐户，您便可以享受SYIHY各项服务。
    <br/>
    <br/>
    
    {1}
    请保管好您的密码,以免丢失。
  
    修改密码：<a href="https://www.syihy.com/forum/password.aspx" target="_blank">https://www.syihy.com/forum/password.aspx</a>
    <br/>
    <br/>
        (如果无法点击该URL链接地址，请将它复制并粘帖到浏览器的地址输入框，然后单击回车即可。该链接使用后将立即失效。)
    <br/>
    <br/>
        注意:请您在收到邮件{2}个小时内({3}前)进行激活，否则该激活码将会失效。{4}天后您的帐户将会失效。
    <br/>
    <br/>
        重新发送激活码：<a href="https://www.syihy.com/forum/active.aspx" target="_blank">https://www.syihy.com/forum/active.aspx</a>
    <br/>
        修改注册email：<a href="https://www.syihy.com/forum/changeemail.aspx" target="_blank">https://www.syihy.com/forum/changeemail.aspx</a>
    <br/>
    <br/>
    <br/>
       关注新闻动态，请访问SYIHY新闻版块：<a href="https://www.syihy.com/forum/news.aspx" target="_blank">https://www.syihy.com/forum/news.aspx</a>
    <br/>
       修改个人档案资料，请访问SYIHY会员中心：<a href="https://www.syihy.com/forum/membercenter.aspx" target="_blank">https://www.syihy.com/forum/membercenter.aspx</a>
    <br/>
       各类精品文章，请访问SYIHY博客：<a href="https://www.syihy.com/forum/bolg.aspx" target="_blank">https://www.syihy.com/forum/bolg.aspx</a>
    <br/>
       更多SYIHY服务，请访问 <a href="http://www.syihy.com/" target="_blank">http://www.syihy.com/</a>
    <br/>
    <br/>
       我们将一如既往、热忱的为您服务！
    <br/>
    <br/>
       www.syihy.com - 提供最全面的信息传播和服务平台
    <br/>
       用户服务支持：www.syihy.com
    <br/>
    <br/>
</pre>