
<div>
  <style type="text/css">.imagesArea1 * { vertical-align: middle; }</style>
  <script type="text/javascript">var source="yueyi2013";sourcesuninfo="ad-14121-20-0-0-5";</script>
  <script type="text/javascript" src="http://jsy.vanclimg.com/Public/adSearch.js"></script>
  <div class="imagesArea1">
    <img src="http://union.vancl.com/images/logo.gif" alt="logo"/>
    <input type="text" id="vanclSearchTxt" />
    <input type="button" id="vanclSearchBtn" value="凡客一下" onclick="singleSearch();" />
  </div>
</div>